// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testdata.proto

package datastreamer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Content struct {
	Fe                   int64         `protobuf:"varint,1,opt,name=fe,proto3" json:"fe,omitempty"`
	Ctp                  int64         `protobuf:"varint,2,opt,name=ctp,proto3" json:"ctp,omitempty"`
	Channel              int64         `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Gate                 []*Gatesignal `protobuf:"bytes,4,rep,name=gate,proto3" json:"gate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Content) Reset()         { *m = Content{} }
func (m *Content) String() string { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()    {}
func (*Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_40c4782d007dfce9, []int{0}
}

func (m *Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Content.Unmarshal(m, b)
}
func (m *Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Content.Marshal(b, m, deterministic)
}
func (m *Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Content.Merge(m, src)
}
func (m *Content) XXX_Size() int {
	return xxx_messageInfo_Content.Size(m)
}
func (m *Content) XXX_DiscardUnknown() {
	xxx_messageInfo_Content.DiscardUnknown(m)
}

var xxx_messageInfo_Content proto.InternalMessageInfo

func (m *Content) GetFe() int64 {
	if m != nil {
		return m.Fe
	}
	return 0
}

func (m *Content) GetCtp() int64 {
	if m != nil {
		return m.Ctp
	}
	return 0
}

func (m *Content) GetChannel() int64 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *Content) GetGate() []*Gatesignal {
	if m != nil {
		return m.Gate
	}
	return nil
}

type Gatesignal struct {
	GateATof             int64    `protobuf:"varint,1,opt,name=GateATof,proto3" json:"GateATof,omitempty"`
	GateBTof             int64    `protobuf:"varint,2,opt,name=GateBTof,proto3" json:"GateBTof,omitempty"`
	Amp                  int64    `protobuf:"varint,3,opt,name=Amp,proto3" json:"Amp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Gatesignal) Reset()         { *m = Gatesignal{} }
func (m *Gatesignal) String() string { return proto.CompactTextString(m) }
func (*Gatesignal) ProtoMessage()    {}
func (*Gatesignal) Descriptor() ([]byte, []int) {
	return fileDescriptor_40c4782d007dfce9, []int{1}
}

func (m *Gatesignal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gatesignal.Unmarshal(m, b)
}
func (m *Gatesignal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gatesignal.Marshal(b, m, deterministic)
}
func (m *Gatesignal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gatesignal.Merge(m, src)
}
func (m *Gatesignal) XXX_Size() int {
	return xxx_messageInfo_Gatesignal.Size(m)
}
func (m *Gatesignal) XXX_DiscardUnknown() {
	xxx_messageInfo_Gatesignal.DiscardUnknown(m)
}

var xxx_messageInfo_Gatesignal proto.InternalMessageInfo

func (m *Gatesignal) GetGateATof() int64 {
	if m != nil {
		return m.GateATof
	}
	return 0
}

func (m *Gatesignal) GetGateBTof() int64 {
	if m != nil {
		return m.GateBTof
	}
	return 0
}

func (m *Gatesignal) GetAmp() int64 {
	if m != nil {
		return m.Amp
	}
	return 0
}

func init() {
	proto.RegisterType((*Content)(nil), "datastreamer.Content")
	proto.RegisterType((*Gatesignal)(nil), "datastreamer.Gatesignal")
}

func init() { proto.RegisterFile("testdata.proto", fileDescriptor_40c4782d007dfce9) }

var fileDescriptor_40c4782d007dfce9 = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x41, 0xeb, 0x82, 0x40,
	0x10, 0xc5, 0x71, 0x57, 0xfe, 0xfe, 0x99, 0x42, 0x62, 0x4f, 0x4b, 0x27, 0xf1, 0xe4, 0x21, 0x3c,
	0xd4, 0x27, 0xb0, 0x0e, 0xdd, 0x25, 0xba, 0x6f, 0x36, 0x5a, 0xa0, 0xbb, 0xe2, 0xce, 0xf7, 0x27,
	0x66, 0xd1, 0xec, 0xf6, 0x7e, 0xef, 0x0d, 0xbc, 0x37, 0x90, 0x12, 0x7a, 0x7a, 0x1a, 0x32, 0xe5,
	0x38, 0x39, 0x72, 0x6a, 0xcb, 0xda, 0xd3, 0x84, 0x66, 0xc0, 0x29, 0xf7, 0x90, 0x5c, 0x9c, 0x25,
	0xb4, 0xa4, 0x52, 0x10, 0x2d, 0xea, 0x28, 0x8b, 0x0a, 0x59, 0x8b, 0x16, 0xd5, 0x0e, 0x64, 0x43,
	0xa3, 0x16, 0xc1, 0x60, 0xa9, 0x34, 0x24, 0xcd, 0xcb, 0x58, 0x8b, 0xbd, 0x96, 0xc1, 0x5d, 0x50,
	0x1d, 0x20, 0xee, 0x0c, 0xa1, 0x8e, 0x33, 0x59, 0x6c, 0x8e, 0xba, 0xfc, 0xed, 0x28, 0xaf, 0x86,
	0xd0, 0xbf, 0x3b, 0x6b, 0xfa, 0x3a, 0x5c, 0xe5, 0x77, 0x80, 0xd5, 0x53, 0x7b, 0xf8, 0x67, 0xaa,
	0x6e, 0xae, 0x9d, 0xdb, 0xbf, 0xbc, 0x64, 0x67, 0xce, 0xc4, 0x9a, 0x31, 0xf3, 0xbe, 0x6a, 0x18,
	0xe7, 0x25, 0x2c, 0x1f, 0x7f, 0xe1, 0xc3, 0xd3, 0x27, 0x00, 0x00, 0xff, 0xff, 0x73, 0xa4, 0xad,
	0x23, 0xf3, 0x00, 0x00, 0x00,
}
